pipeline {
    agent any
    parameters {
        string(name: 'TAG', defaultValue: 'latest', description: 'Tag dell\'immagine Docker')
    }
    environment {
        GIT_URL = 'https://github.com/Andrea-Panicucci-git/formazione_sou_k8s'
        IMAGE_NAME = 'andreapanicucci/docker-image'   
        DOCKER_CREDENTIALS_ID = 'DockerHub'  
    }

    stages {
        stage('Pulizia workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Clona repo git') {
            steps {
                script {
                    sh "git clone ${GIT_URL}"
                }
            }
        }
        stage('Docker login') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                    }
                }
            }
        }
        stage('Lista helm') {
            steps {
                sh "helm list"
            }
        }
         stage('Creazione namespace') {
            steps {
                // Crea il namespace formazione-sou
                sh "kubectl create namespace formazione-sou || echo 'namespace gia creato'"
            }
        }
        stage('Install Helm chart') {
            steps {
                // Usa il percorso relativo al workspace e il parametro TAG definito
                sh "helm install formazione-sou \"${WORKSPACE}/formazione_sou_k8s/charts/flask-app\" -n formazione-sou --set image.tag=${params.TAG} || true "
            }
        }
         stage('Lista helm2') {
            steps {
                sh "helm list -A"
            }
        }
    }
}
