# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"

  # Configurazione rete

  config.vm.network :forwarded_port, guest: 8080, host: 8080  
  config.vm.network "private_network", ip: "192.168.3.22"

  # Configurazione provider VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # Provisioning Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    
  end
end
